# Generated by Django 5.1 on 2026-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name'], 'verbose_name': 'Joueur', 'verbose_name_plural': 'Joueurs'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configuration du site', 'verbose_name_plural': 'Configuration du site'},
        ),
        migrations.AlterModelOptions(
            name='teamstats',
            options={'verbose_name': 'Statistiques équipe', 'verbose_name_plural': 'Statistiques équipes'},
        ),
        migrations.AlterModelOptions(
            name='trainingschedule',
            options={'verbose_name': "Horaire d'entraînement", 'verbose_name_plural': "Horaires d'entraînement"},
        ),
        migrations.AddField(
            model_name='team',
            name='ranking_api_url',
            field=models.URLField(blank=True, help_text='Ex: https://api-dofa.fff.fr/api/compets/434770/phases/1/poules/2/classement_journees?page=1', null=True, verbose_name='URL API classement FFF'),
        ),
    ]
