# Generated by Django 5.1 on 2026-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_player_options_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cp_no',
            field=models.CharField(blank=True, help_text='Identifiant compétition (ex: 434763)', max_length=20, null=True, verbose_name='FFF cp_no'),
        ),
        migrations.AddField(
            model_name='team',
            name='phase_no',
            field=models.IntegerField(default=1, verbose_name='FFF phase'),
        ),
        migrations.AddField(
            model_name='team',
            name='poule_no',
            field=models.IntegerField(default=1, verbose_name='FFF poule'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ranking_api_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL API classement FFF'),
        ),
    ]
