# Generated by Django 5.1 on 2026-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_team_cp_no_team_phase_no_team_poule_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notre Club', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='club/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Club',
                'verbose_name_plural': 'Page Club',
            },
        ),
    ]
