# Generated by Django 5.1 on 2026-04-24 11:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_galleryphoto_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('foot-a-8', 'Foot à 8'), ('foot-a-5', 'Foot à 5')], max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('coaches', models.TextField(blank=True, help_text='Noms des coachs, un par ligne')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page catégorie (Foot à 8 / Foot à 5)',
                'verbose_name_plural': 'Pages catégories (Foot à 8 / Foot à 5)',
            },
        ),
    ]
