# Generated by Django 5.1 on 2026-04-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_categorypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('foot-a-8', 'Foot à 8'), ('foot-a-5', 'Foot à 5')], max_length=20, verbose_name='Catégorie')),
                ('name', models.CharField(blank=True, help_text='Si aucune équipe sélectionnée ci-dessus, entrez un nom ici', max_length=100, verbose_name='Nom personnalisé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team-presentations/', verbose_name='Photo')),
                ('coaches', models.TextField(blank=True, help_text='Un nom par ligne (ex: Jean Dupont)', verbose_name='Staff / Coachs')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='club.team', verbose_name='Équipe (optionnel)')),
            ],
            options={
                'verbose_name': 'Présentation équipe',
                'verbose_name_plural': 'Présentations équipes (Foot à 5 / Foot à 8)',
                'ordering': ['order'],
            },
        ),
    ]
