# Generated by Django 5.1 on 2026-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_teampresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.TextField(blank=True, help_text='Un nom par ligne', verbose_name='Staff / Coachs'),
        ),
    ]
