# Generated by Django 5.1 on 2026-04-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_team_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Ex: Seniors, U17, Foot à 5, Futsal...', max_length=100, verbose_name='Catégorie')),
                ('form_url', models.URLField(verbose_name='Lien Google Form')),
                ('description', models.TextField(blank=True, verbose_name='Description (optionnel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Détection',
                'verbose_name_plural': 'Détections',
                'ordering': ['order'],
            },
        ),
    ]
