# Generated by Django 5.1 on 2026-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_sponsor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_no', models.CharField(max_length=20)),
                ('phase_no', models.IntegerField()),
                ('poule_no', models.IntegerField()),
                ('cl_no', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('pts', models.IntegerField(default=0)),
                ('j', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('n', models.IntegerField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('bp', models.IntegerField(default=0)),
                ('bc', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classement (secours)',
                'verbose_name_plural': 'Classements (secours)',
                'ordering': ['rank'],
                'unique_together': {('cp_no', 'phase_no', 'poule_no', 'cl_no')},
            },
        ),
    ]
