# Generated by Django 5.1 on 2026-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_classemententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassementFetchLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_no', models.CharField(max_length=20)),
                ('phase_no', models.IntegerField()),
                ('poule_no', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('cp_no', 'phase_no', 'poule_no')},
            },
        ),
    ]
